ARDUINO_DIR   = /home/lars/applications/arduino-1.6.3

ARCHITECTURE  = avr
BOARD_TAG     = mega
BOARD_SUB     = atmega2560

MONITOR_PORT  = /dev/ttyACM1
MONITOR_BAUDRATE	= 57600

include /home/lars/applications/arduino-makefile/Arduino.mk
