ARDUINO_DIR   = /home/robin/applications/arduino-1.6.3

ARCHITECTURE  = avr
BOARD_TAG     = mega
BOARD_SUB     = atmega2560
MONITOR_PORT  = /dev/ttyACM2
MONITOR_BAUDRATE	= 57600

include /home/robin/applications/arduino-makefile/Arduino.mk
