# http://mrbook.org/blog/tutorials/make/

all:
	g++ -I ../SF/ -I ./ main.cpp send.cpp player_test.cpp stack_test.cpp hill_test.cpp king_test.cpp ../SF/Player.cpp ../SF/Hill.cpp ../SF/King.cpp ../SF/Stack.cpp ../SF/StackCounter.cpp -o test
